### PR TITLE
Submission: Merged open-source contribution to Reth

### PR DESCRIPTION
**Pull request by fabianzeiher**
# Assignment Proposal

## Title

Open source contribution to reth

## Names and KTH ID

- Fabian Zeiher (zeiher@kth.se)

## Deadline

- Task 3

## Category

- Open source

## Description

Reth is an execution layer for ethereum implemented in Rust.
The project is still in active development with a very open and friendly community.
I found a [good issue](https://github.com/paradigmxyz/reth/issues/5906) that is very self-contained and seemed reasonable.
The friendly conversation with the maintainer and merged pull request can be found here: [fix: randomly sample peers in `NetworkState::announce_new_block()` for block propagation](https://github.com/paradigmxyz/reth/pull/5930)

**Relevance**

Reth implements a core component of the ethereum blockchain.

### CODE REVIEW

**Comment by fabianzeiher** [comment]
@monperrus Still hoping for A.

**Comment by monperrus** [comment]
Clear pass, end-to-end contribution to high profile open source.
Well done @cetceeve!

**Comment by fabianzeiher** [comment]
Awesome! Thank you.

**Comment by monperrus** [comment]
Not only you can be proud of your A, but also to be the only one to achieve this feat :100:

**Pull request merged**
