### PR TITLE
Submission: Essay on digital passports using DLTs

### PR DESCRIPTION
**Pull request by fabianzeiher**
# Assignment Proposal

## Title 
_Digital Passport - Better Security and Privacy with Blockchain Technology_

# Names and KTH ID
- Fabian Zeiher (zeiher@kth.se)

# Deadline
- Task 1

# Category
- Essay

# Description

International Border Crossings remain a daunting procedure for many even in the "globalized" world we live in today.
Outside of supranational organisation (e.g. European Union) we rely on VISAs to regulate entry, exit and duration of stay in a foraign country.
Often additional information like work-permits and state social welfare benefits are only granted to holders of specific VISAs.
Since the system today is pretty much entirly paper based this system comes with major risks and inefficiencies.

All international travelers share stories of endless cueing at immigration to receive a simple stamp in their passports.
In many lower-income countries the need to bribe immigration officiers in cash in order to not be denied entry is common.
Once inside the foreign country loosing once passport can be very painful, as usually only the embassy of ones home country can reissue a passport and often this process takes weeks to complete.
Connected with the loss of once passport is a major risk for identity theft and forgery of passports.

Blockchain technology is especially interesting for replacing tradiditional passports and VISAs as it can fully replace all existing functions of Passports and VISAs as well as significantly improve the security for states and passport holders alike.
Being forgery proof is one of blockchains stand-out features which helps states in their border control efforts and mitigates risks of identity theft.
For passport holders having a digital document greatly simplifies reissuance, which could be as simple as authenticating oneself on the blockchain.
Of course, moving to a digital solution also opens up new security vulnerabilities like hacking or lack of access to digital infrastructure.

In the essay I plan to explore the following:
- Current Passport and VISA limitations
- Digital Identities on Blockchain as the underlying foundation
- A possible implementation
- Risks and other Considerations that emerge with digital passports (e.g. privacy)

**Relevance**

Digital Passports can be seen as a form of Digital Identity on the Blockchain.
Blockchain are a very interesting technology to create digital passports for two reasons.
The distributed de-centralized nature of blockchain is crutial for digital passports as states would never accept a digital passport technology that was centrally managed in a single state (e.g. by a large company in the USA or China).
The security and defence against attacks are very important because digital passports store incredibly important information.
There already is a digital passport implementation called [Known Traveller Digital Identity](https://ktdi.org) that can be used for travels between the Netherlands and Canada.

### CODE REVIEW

**Comment by fabianzeiher** [comment]
Please note, the essay title has been updates to better reflect the actual content of the essay.

**Comment by pierrelefevre** [comment]
# Feedback for Fabian Zeiher
## Digital Passport - Better Security and Privacy with Blockchain Technology

Thanks for the great essay Fabian! It was a great read and very approachable, I'd love to see this tech in use. Here is some feedback according to the criteria.

### High level
#### Strengths
- The essay is well written and easy to read, I think the topic is super interesting and the explanation of zero knowledge proofs are very approachable for being a complex topic.
- I appreciate the critical viewpoint towards these implementationslike KTDI. It seems many of the solutions use crypto and blockchain as buzzwords while still intending to keep everything centralized.
    - For example Worldcoin on the surface seems to be a decentralized platform, but it appears they are the only ones providing the identity verification service, effectively making them a centralized authority. The orb hardware and many other services being open source does show a step in the right direction though.
- The sources seem recent and relevant, most of them being proper research papers.
- The reflection and conclusion provide a good summary and critical analysis of the topic.


#### Weaknesses
- The language in the essay seems to have many small mistakes that could have been caught with a simple spell checker. While the content is not directly affected, it does make the essay feel less professional.
- While this may not be possible due to the length limit, I would love some more in depth explanations of the different solutions, and how they would compare from a user's perspective. 
- The essay is very focused on the technical aspects of the solutions, while it does mention the user's perspective a few times, I would love to see a discussion about how this tech can be rolled out in a way that's inclusive to all, for example those which may not have access to a smartphone.


### Details
#### Structure
In my opinion, the essay is well divided into clear sections. The introduction is quite long but feels very fit for the topic as there is a lot to introduce. The sections are well divided into clear topics which build upon the previous ones. The conclusion and reflection provide a good summary and great critical analysis of the topic.

#### Substance
The essay is very well researched and the sources seem relevant and recent. The language is easy to read and explains complex topics in a way that is approachable. As mentioned above, I would love to see a more in depth discussion about the different solutions and how they compare from a user's perspective, as well as how this tech can be rolled out in a way that's inclusive to all. Overall however I think it's a great introduction to the field of zero knowledge proofs and how they can be implemented as a digital passport.

### Small errors
- "This is facilitated once again by Private Key Cryptography" is the first time private keys are mentioned
- ”Zero-**Kow**ledge Proof" typo in section 3 
- "a traveller could **proof** to be more than 18 years old" probably should be **prove**?
- Inconsistent casing of Worldcoin or WorldCoin

### Generative AI Disclaimer 
I certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

**Comment by fabianzeiher** [comment]
@pierrelefevre  Super relevant feedback, thank you! Yes, all the topics need some more explanation but I was too deep into the research and running out of space in the essay fast. 😅

**Comment by javierron** [comment]
Hello @cetceeve, thanks for the submission!

**Pull request merged**
