### PR TITLE
Add week2 presentation proposal, fe vs solidity

### PR DESCRIPTION
**Pull request by pierrelefevre**
# Assignment Proposal

## Title

_Fe vs Solidity: Choosing the right language for your Ethereum Smart Contract_

## Names and KTH ID

  - Pierre Le Fevre (pierrelf@kth.se)

## Deadline

- Week 2

## Category

- Presentation

## Description

My presentation will compare Fe and Solidity, two smart contract languages for the Ethereum blockchain. 
I'll begin with a short introduction to smart contracts and Ethereum before diving into:
- The rationale for using different languages in smart contract development.
- Key design and security features of Fe versus Solidity.
- Brief code comparisons to illustrate language differences.
 

**Relevance**

The choice between Fe and Solidity impacts the security, maintainability, and success of smart contracts. Understanding their differences helps in selecting the right tool for building robust and efficient applications on Ethereum.

### CODE REVIEW

**Comment by pierrelefevre** [comment]
For transparency, inspiration is from:

https://github.com/KTH/programmable-society/issues/1#issuecomment-1265270326 and https://github.com/KTH/programmable-society/issues/1#issuecomment-1257770216

**Comment by Jacarte** [comment]
> Missing student registration :zeiher
> 
> If not from your group, fetch the upstream.

This seems a glitch in our checking system. We are working to fix it.

**Comment by Jacarte** [comment]
@pierrelefevre we agreed on this presentation. Yet, we won't merge until we fix the issue. Looking forward your presentation :)

**Comment by javierron** [comment]
@pierrelefevre  BTW, there is another presentation about Fe and Solidity, https://github.com/KTH/programmable-society/pull/41.

Try to keep as little overlap as possible between the presentations. This presentation's focus should be on the differences.

**Pull request merged**
