### PR TITLE
Add essay - pierrelf

### PR DESCRIPTION
**Pull request by pierrelefevre**
# Assignment Proposal

## Title 
_Navigating the Legal Labyrinth: The Challenges of Operating Cryptocurrency Exchanges_

# Names and KTH ID
- Pierre Le Fevre (pierrelf@kth.se)

# Deadline
- Task 1

# Category
- Essay

# Description
This essay will explore the complex legal landscape that cryptocurrency exchanges must navigate. As digital currencies gain popularity, regulatory scrutiny and legal challenges have intensified, posing significant hurdles for exchange operators. The essay will delve into various aspects of these challenges in regulatory compliance, like Anti-Money Laundering and Know Your Customer Regulations, Cross-Border Legal Issues, Consumer Protection, Taxation and Financial Reporting and Legal Recourse for Users.

**Relevance**
Understanding the legal difficulties of running a cryptocurrency exchange is crucial in today's rapidly evolving digital currency landscape, and unclear legal actions by regulatory bodies like the SEC. [Example: SEC charges Kraken for operating as an unregistered securities exchange](https://news.ycombinator.com/item?id=38356361)

### CODE REVIEW

**Comment by Jacarte** [comment]
Hi @pierrelefevre.
Please check the grading criteria related to the number of words. The automated checking is failing due to the word count. The grading criteria said 2400-2600 words count, yours is 1280.

**Comment by pierrelefevre** [comment]
> Hi @pierrelefevre.
> Please check the grading criteria related to the number of words. The automated checking is failing due to the word count. The grading criteria said 2400-2600 words count, yours is 1280.

Word count was altered for essays using generative ai during the last lecture 🌞

**Comment by Jacarte** [comment]
> > Hi @pierrelefevre.
> > Please check the grading criteria related to the number of words. The automated checking is failing due to the word count. The grading criteria said 2400-2600 words count, yours is 1280.
> 
> Word count was altered for essays using generative ai during the last lecture 🌞

Noted !
Thanks for bringing this up

**Comment by pierrelefevre** [comment]
I'd like to give the "go" for feedback!

**Comment by fabianzeiher** [comment]
# Feedback for Pierre

Thanks for the great essay Pierre. It was a very enjoyable read and it really helped me to gain some insight into the regulatory problems regarding crypto exchanges.

## Strengths

- The introduction into the topic was very clear, even for someone with no prior knowledge.
- The relevant case studies are well written and concise.
- I really enjoyed the reflection part, that encouraging a more grassroots approach to projects in the crypto space.

## Weakness

- I would have enjoyed a bit more technical details.
- The references are not following an academic style. Not really a problem for an essay, but it makes it hard to judge the quality of the references at a glance.

## Details

### Introduction & Background

These sections are - like the rest of the essay - really well written. Even as a reader who has no knowledge about crypto exchanges and legal issues. Right at the beginning some USA institutions, namely SEC, CFTC, IRS are mentioned. As I have little knowledge about the United States government institutions I would have needed an explanation about the mission of these organisations. I really liked the chapter on laws of AML and KYC. The purpose and reasoning behind these laws was clearly explained and it was easy to understand how DLT based companies could struggle to comply with these laws. However I find that a more technical introduction into the operation of crypto exchanges is missing from the essay.

### Case studies

The chosen case studies seem very relevant, even I had head of some of them in the news. They were very clearly described and presented in a concise manner highlighting the most important aspects. I liked that each use case emphasised different higher-level concepts. Personally though I would have appreciated more technical details, about the technologies these companies were using and why they failed to comply with regulations. Maybe also some insights if it would have even been possible to comply with regulations.

### Conclusion and Reflection

The conclusion nicely summarises the essay. I really appreciated the reflection part. I appreciate that the reflection states a clear and strong opinion and includes actionable recommendations.

### Overall

**Structure**

The essay is well structured and all parts have the right balance. The ordering of the chapters makes sense. Putting the Reflection after the Conclusion feels unconventional, but I think it was the right decision as the reflection departs quite drastically from the narrative and language of the rest of the essay.

**Language**

I could not find any language mistakes. (though I am probably the wrong person to ask)
Personally I think the language in the reflective part was a bit too nonchalant. The reflection looses a bit of credibility from the language, which is a shame since the opinions stated are very valid and agreeable.

**References**

The essay contains references from official government sources as well as mostly high quality news journals. The fact that only a list of links was provided made the references hard to judge at a glance. The essay could gain some credibility by citing some academic papers. Some useful additional academic material could have possibly been:

Arslanian, H. (2022). Crypto Exchanges. In: The Book of Crypto. Palgrave Macmillan, Cham. https://doi.org/10.1007/978-3-030-97951-5_18

Goforth, C. R. (2022). Critiquing the SEC's Ongoing Efforts to Regulate Crypto Exchanges. Wm. & Mary Bus. L. Rev., 14, 305.

Alekseenko, A. P. (2023). Model Framework for Consumer Protection and Crypto-Exchanges Regulation. Journal of Risk and Financial Management, 16(7), Article 7. https://doi.org/10.3390/jrfm16070305

## Generative AI Disclaimer

I certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

**Comment by pierrelefevre** [comment]
@cetceeve Thanks for the great feedback!

**Comment by javierron** [comment]
Hello, @pierrelefevre, can you rebase your fork with the latest changes to get the CI passing? Thanks!

**Comment by pierrelefevre** [comment]
@javierron Done! Seems to be passing the tests now

**Comment by javierron** [comment]
@pierrelefevre Thanks for the contribution!

**Pull request merged**
