### PR TITLE
Pressentation Proposal Koen

### PR DESCRIPTION
**Pull request by sifisKoen**
# Assignment Proposal

## Title

Meet Fe: The Fresh Face to Ethereum Programming

## Names and KTH ID

* Iosif Koen (iosif@kth.se)

## Deadline

* Week 2

## Category

* Presentation

## Description

I plan to present the Fe programming language, witch is a new catting edge programming language for Ethereum. Fe language is a modern and innovative programming language. In the first part I will explain briefly what it **Ethereum** and what is **blockchain** (explaining what is a block and what is the chain). Then we will talk about Fe language and its dynamics.

* Briefly explanation about the language. (Theoretical)
* Explain that the language is used to build Ethereum VMs (Personal favor 😄)
* Presenting couple showcases of the language.
* Finally we will explain a simple code on how we can make a block and add it to the chain of the Ethereum. (Don't know if it will work properly)

**Relevance**
This topic is very relevance for the next week because I will present a programming language for blockchain and Ethereum witch is in the edge of technology (sins 2021). It one of the most innovative languages for this purpose with a very active GitHub community, with that I want to say that it is not only relevance for the next week but also with the whole idea of the course (open source) using GitHub.

### CODE REVIEW

**Comment by javierron** [comment]
@sifisKoen Thanks for the proposal. It is very relevant for the course. 
It is accepted, however you need to fix the path of the reademe file. It needs to contain your KTH username. 

Also, try to coordinate with https://github.com/KTH/programmable-society/pull/40 , so there is as little overlap as possible between the presentations.

**Comment by sifisKoen** [comment]
Hello @javierron I don't think I am willing to change my whole presentation for a common topic in a presentation witch will compare two programming languages.

If you think there is an over lap just decline my proposal because it was second. :smile: 

Also what do you mean my "KTH account name"? I renamed my directory where I have my README folder on my KTH mail first half. (iosif@kth.se). So I don't know.

**Comment by javierron** [comment]
@sifisKoen you also need to remove the previous file (the one with "koen" in the path) from the pull request.

Currently, there is no overlap of topics: According to your description, your presentation will focus on Fe; while the other presentation will focus on differences of Fe and Solidity.

These are both good presentation topics, but in practice there could be some repeated content, and we want to minimize that.

**Comment by sifisKoen** [comment]
@javierron I will **not** talk about Solidity in the way of full comparison. I will just brief explain couple things. :smile: 
For example I will have only one slide to be more specific

**Comment by sifisKoen** [comment]
@javierron thank you for the merge. :smile: 
And thank you for your guidance.

**Pull request merged**
