### PR TITLE
Commit essay

### PR DESCRIPTION
**Pull request by sifisKoen**
# Assignment Proposal

## Title
Beyond Blockchain: Unpacking the Innovations of Internet Computer Protocol (ICP).

## Names and KTH ID
* Iosif Koen (iosif@kth.se)

## Deadline
* Task 1

## Category
* Essay

## Description
In this essay I will try to explore and unpack the idea and innovation behind the Internet Computing Protocol (ICP). ICP is a blockchain protocol which aims to extend the functionality of the public internet. That means not only data exchange but also decentralized computing. So ICP it's much more than an other typical block chain protocol, it is much more than that. As I see they are trying to create a decentralized internet where independent data centers all over the world will be able to combine their computing power to host software and internet services. In this point I would like to give kudos to Mojtaba and Javier (TAs) for their guidance to this topic and help.

**Relevance**
Understanding the power and alternative usages of blockchain is one of the main core outcomes of the course, and ICP provides this prossibility because we can see an other perspective of a blockchain instead of classic examples (DEFI, NfTs). Also this topic combines knowledge from an other course that I took from KTH (DevOps and Distributed systems). Also it will help be to improve my critical thinking on multiple areas of computer science combining multiple field as I explained, because I want to write also my personal thoughts and reflections on this topic with my prior knowledge. Last but not least I would like to mention that my research will be mostly from ICP's web page using their white paper and documentation, I will try to find more recourses from paper pools such as IEEE explore for better conclusions and understanding.
I would like to share this information (Internet Protocol Web page)[https://internetcomputer.org/]

### CODE REVIEW

**Comment by bbaudry** [comment]
@sifisKoen thanks for contributing an essay to the course!
 can you fix it to pass all checks?
thanks!

**Comment by sifisKoen** [comment]
@bbaudry Ok sir I will remove some parts and I will re-upload my essay. Thank you for the understanding.

**Comment by sifisKoen** [comment]
@bbaudry Hello sir. My essay is ready for grading and feedback. 

Thank you again for your understanding.

**Comment by lerjevik** [comment]
# Feedback for Essay: ”Beyond Blockchain: Unpacking the Innovations of Internet Computer Protocol (ICP)”

## High-level strengths and high-level weaknesses

### Strengths
* The vast amount of research put into this essay and how it provides a concrete summary of the core features as well as workflow of the protocol
* An interesting reflection, where both advantages and limitations of ICP are brought up
* A take home message is included for the reader to take with them after reading the essay

### Weeknesses
* For the references, one suggestion would be to use academic styling, such as [Oxford](https://www.umu.se/en/library/search-write-study/writing-references/oxford-writing-reference-list/) in order for the reader to get more overview about the references, e.g., their standard and publishing date
* I would prefer if all figures were referenced in the text, since it would strengthen the reasoning offered by the text
* By adding some figure caption you would also offer some guidance to the reader about what to focus on in the figures

## In-depth analysis of essay

In this section, I will provide some more in-depth feedback about the different sections of the report:

### ”First step in Internet Computer”

A clear and concise summary of the role of ICP. It was interesting to read that this is considered the third most important invention in the blockchain area. What are the other two? Maybe you could add something along the lines of "...third most important invention in the blockchain area, after X and X", just to put this invention in perspective for the reader.

One suggestion would be to introduce the topic by giving some more concrete problematization of the modern day internet, e.g., describe a scenario in which modern day internet fails and how ICP would be a more suitable option in that case. An example can be found [here](https://www.coinbase.com/learn/crypto-basics/what-is-internet-computer), under "How does ICP work?". I believe that this would help motivate the topic of the essay and catch the interest of the reader. Also, what's mentioned about decentralization there could be linked to the reflection and perhaps the take home message, in order to tie back to the introduction.

### ”Internet Computer Protocol the Basics”

I think this section gives a good summary of how ICP works, and I like the way the true scaling approach was introduced. I also like the fact that you've divided the technoloy heavy sections into two, i.e., one introductory section and one where you go more into depth, sine it allows for the reader to get a basic familiarity and overview before deep-diving into the topic. 

As a suggestion for improvement, I think that the figure could be referenced in the text. More specifically, the definition of "node machines" could be clarified in the text since it is included in the figure. Also, a caption with the source of the statistics presented in the figure could be included.

### ”Internet Computer Protocol in More Depth”

It becomes evident that the author put a lot of time and effort into researching the topic.This section is very detailed and well structured, and offers great insight into the technicalities of ICP. 

In the architecture-section, some more details regarding vertical vs. horizontal scaling could be provided. A reference to the developer paper could be included where you reference it, e.g., in the consensus-section. Moreover, I think the definition of cycles could be introduced to the user in the text, in order to guide the reader a bit when looking at the figure in the execution-section. In general, parallells to other blockchain platforms, which the reader might be more familiar with, e.g., Ethereum, could be drawn (e.g., stating that cycles correspond to gas). [This](https://changelly.com/blog/what-is-internet-computer/) article offers an interesting comparison between Ethereum and ICP. 

### ”Let’s Google Some Smart Contracts”

A very clear description of the workflow, and the figure here is very helpful. A suggestion would be to write out the abbrevation of GFS, since this would facilitate for readers who do not know what it stands for to look it up. 

### ”Reflection”

Interesting reflection! It is mentioned that the documentation was a bit hard to navigate, which makes the work even more impressive. I think its good that you do not just mention the advantages of the protocol but also its limitations, i.e., the difficulties with reading the documentation. Moreover, I like that the reader is left with a take-away message.

I think something that would be interesting to address as well would be the concerns regarding centralization, i.e., like in [this](https://www.blockzeit.com/a-breakdown-of-the-revolutionary-internet-computer-protocol/) and [this](https://medium.com/coinmonks/the-advantages-and-disadvantages-of-developing-applications-on-the-internet-computer-blockchain-3008573508e0) article. 

## Disclaimer about LLM usage

I certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

**Comment by monperrus** [comment]
ack, thanks @lerjevik. grade now in Canvas.

**Pull request merged**
