### PR TITLE
Contract Proposal: Transparency and access to safety critical data

### PR DESCRIPTION
**Pull request by fabianzeiher**
# Assignment Proposal

## Title

A digital passport for your physical items

## Names and KTH ID

  - Iosif Koen (iosif@kth.se) 
  - Fabian Zeiher (zeiher@kth.se)

## Deadline

- Task 1

## Category

- Smart Contract Protocol Development

## Description

We plan to create a dApp that allows users to create a digital passport for physical items and make the information associated with these items easily accessible.
To bring an item into the application users can create a QR-Code, that is stuck onto the item. The QR code is an encoding of the key that uniquely identifies this item in the cloud. Other users can scan the QR-Code to easily access the data of this item on the blockchain. This has the potential to break down data silos, e.g. across company databases.
The users of our application can choose which data to associate with the item.
Each item will have an owner, that can change the information about the item, but all changes will be visible in the item passport.
We also have the role of manufacturer, which can change information in case there was a mistake on the first entry or if some critical flaw was discovered. Initially, the contract owners will decide who is a trusted manufacturer, but in the future, this could be managed by a DAO.

We will use Foundry to compile, (fuzz) test, and deploy our smart contracts.
We can utilize Foundry GitHub-actions integration for a CI-CD pipeline.
We will use Vyper as the smart contract language.
An ERC721 (NFT) contact will be used to represent the items.
We are currently planning to run on an Ethereum Layer 2 chain to reduce gas fees.
We plan to create a website as our user interface, where users can easily check the item passport and see all the associated information. Since QR codes play an important role in our application the website design will be optimized for mobile devices.

**Relevance**

This topic is relevant because it leverages blockchain technology to enable transparency, integrity, and publicly accessible data. There are multiple research papers out there investigating this use case.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @cetceeve
Thanks for the draft. 
The topic is generally interesting. Have you given more thought to the specific use case and tech stack?

**Comment by fabianzeiher** [comment]
## Notes from the TA session (08.12):

- Merkle trees are likely not a useful architectural approach. Simple lists will be just fine.
- _The Graph_ would be overengineered, but it could be useful.
- We represent the physical items as NFTs (ERC721 but in Vyper).
- We spoke a lot about ownership and access. (But this is still open discussion)
  - We want to represent item ownership and item manufacturer
  - Initially, the contract owner decides who are trusted manufacturers
  - future work: move this into a DAO
- The QR-Code concept is good
  - we discussed the problem of identity and explored some esoteric solutions
- The passport concept is good

**Comment by fabianzeiher** [comment]
@javierron @sifisKoen I have updated the proposal with the results of our discussion from Friday. 🙂

**Comment by javierron** [comment]
Hello @cetceeve @sifisKoen. LGTM, looking forward to the implemented contract.

**Pull request merged**
